name: xr-scipy-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy=1.13
  - pandas=0.21.0
  - xarray
  - scipy=1.0
  - numpydoc=0.7.0
  - matplotlib=2.1.2
  - ipython=6.2.1
  - sphinx=1.5
  - sphinx-gallery
  - flake8
